### PR TITLE
Quick logo attempt.  Closes #1

### LINKED ISSUE #1: Logo?
It would be nice to have one other than the GH default

### PR DESCRIPTION
**Pull request by molpopgen**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
While this is clearly the most important tree in the universe (has to be with this seed, right?),  it's not the most inspiring logo ever. I've never been too bothered about logos personally, but I agree they are important. 

I guess one requirement might be that the logo should incorporate the word 'tskit' in there somewhere? Maybe we could make a set of trees that somehow spell tskit?

Anyone else have any thoughts?

**Comment by ashander** [comment]
A competitor emerges (by @petrelharp for his poster, I think?)

https://github.com/petrelharp/ftprime_ms/blob/7a66216376611b4e0dc607927bc22dba60fea823/talks/poster/tskit_logo.pdf

tskit_logo

**Comment by jeromekelleher** [comment]
I love it!

**Comment by hyanwong** [comment]
Obsoleted by https://github.com/tskit-dev/administrative/pull/8. Can close this one

**Comment by petrelharp** [comment]
obsoleted. thanks a bunch @hyanwong !!

**Pull request closed without merging**
